-- v1 -> v2 (PLAN.md §2.3). Generated by `pnpm db:generate`, then hand-edited:
-- drizzle-kit emitted `ALTER TABLE ... ADD <col> NOT NULL` with no default,
-- which fails on any v1 database that has rows. This rebuilds `courses` and
-- `plan_entries` instead and backfills v1 state. Checked against a real v1
-- database (built at 066bf80, 3 entries added) as well as an empty one; see
-- spec/boot-sync.test.ts.
--
-- Foreign keys must be off while this runs (db.ts sets foreign_keys = OFF
-- before migrate(); better-sqlite3's default is ON), or dropping `courses`
-- fails on plan_entries' reference. db.ts runs foreign_key_check afterwards.
CREATE TABLE `meta` (
	`key` text PRIMARY KEY NOT NULL,
	`value` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `plans` (
	`id` text PRIMARY KEY NOT NULL,
	`years` integer DEFAULT 3 NOT NULL,
	`summer_years_json` text DEFAULT '[]' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
--> statement-breakpoint
DROP TABLE `incompatibilities`;
--> statement-breakpoint
DROP TABLE `requisite_nodes`;
--> statement-breakpoint
-- courses: copy the v1 rows with placeholder values; the boot sync
-- (src/lib/catalogue-sync.ts) overwrites them straight after, or marks them
-- retired if the catalogue no longer has them.
CREATE TABLE `__new_courses` (
	`code` text PRIMARY KEY NOT NULL,
	`subject` text NOT NULL,
	`number` integer NOT NULL,
	`level` integer NOT NULL,
	`title` text NOT NULL,
	`units` integer NOT NULL,
	`summary` text NOT NULL,
	`description` text NOT NULL,
	`offered_json` text NOT NULL,
	`requisite_text` text,
	`rule_json` text,
	`parse_status` text NOT NULL,
	`incompatible_json` text NOT NULL,
	`origin` text NOT NULL,
	`source_url` text NOT NULL,
	`catalogue_year` integer NOT NULL,
	`retired` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
INSERT INTO `__new_courses` (`code`, `subject`, `number`, `level`, `title`, `units`, `summary`, `description`, `offered_json`, `requisite_text`, `rule_json`, `parse_status`, `incompatible_json`, `origin`, `source_url`, `catalogue_year`, `retired`)
SELECT `code`, `subject`, CAST(substr(`code`, 5) AS INTEGER), (CAST(substr(`code`, 5) AS INTEGER) / 1000) * 1000, `title`, `units`, '', '', '[]', NULL, NULL, 'none', '[]', 'catalogue', 'https://programsandcourses.anu.edu.au/2026/course/' || `code`, 2026, 0
FROM `courses`;
--> statement-breakpoint
DROP TABLE `courses`;
--> statement-breakpoint
ALTER TABLE `__new_courses` RENAME TO `courses`;
--> statement-breakpoint
-- v1 had one global plan with no owner. Its entries are kept under a plan id
-- no cookie can produce (cookies are 22-char base64url), so the migration
-- trail keeps old state without handing it to a random browser. Only created
-- when there is v1 state to keep.
INSERT INTO `plans` (`id`, `years`, `summer_years_json`, `created_at`, `updated_at`)
SELECT 'legacy', 3, '[]', CAST(strftime('%s', 'now') AS INTEGER) * 1000, CAST(strftime('%s', 'now') AS INTEGER) * 1000
WHERE EXISTS (SELECT 1 FROM `plan_entries`);
--> statement-breakpoint
CREATE TABLE `__new_plan_entries` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`plan_id` text NOT NULL,
	`course_code` text NOT NULL,
	`year` integer NOT NULL,
	`period` text NOT NULL,
	`slot` integer NOT NULL,
	FOREIGN KEY (`plan_id`) REFERENCES `plans`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`course_code`) REFERENCES `courses`(`code`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
-- the unique indexes exist before the copy so INSERT OR IGNORE drops the v1
-- duplicates they forbid (same course twice in the plan)
CREATE UNIQUE INDEX `plan_slot_uq` ON `__new_plan_entries` (`plan_id`,`year`,`period`,`slot`);
--> statement-breakpoint
CREATE UNIQUE INDEX `plan_course_uq` ON `__new_plan_entries` (`plan_id`,`course_code`);
--> statement-breakpoint
-- v1 term_index 0..5 = Y1S1, Y1S2, Y2S1, ... ; slots numbered per term in
-- insertion order; a v1 term with more than 4 courses keeps the first 4.
INSERT OR IGNORE INTO `__new_plan_entries` (`id`, `plan_id`, `course_code`, `year`, `period`, `slot`)
SELECT `id`, 'legacy', `course_code`, `term_index` / 2 + 1, CASE `term_index` % 2 WHEN 0 THEN 'S1' ELSE 'S2' END, `slot`
FROM (
	SELECT `id`, `course_code`, `term_index`, row_number() OVER (PARTITION BY `term_index` ORDER BY `id`) - 1 AS `slot`
	FROM `plan_entries`
)
WHERE `slot` < 4
ORDER BY `id`;
--> statement-breakpoint
DROP TABLE `plan_entries`;
--> statement-breakpoint
ALTER TABLE `__new_plan_entries` RENAME TO `plan_entries`;
